datainc/urls.py
from django.conf.urls import patterns,url
from django.contrib import admin
from django.views.generic import TemplateView,RedirectView
from data_incubator import views
admin.autodiscover()
admin.site.site_header = 'Data Incubator Administration'
admin.site.site_title = 'Data Incubator Administration'

# app and api URL redirections

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', RedirectView.as_view(url='/app/questions/', permanent=False), name='index'),
    url(r'^app/base.html$', TemplateView.as_view(template_name='base.html')),
    url(r'^app/questions/$', views.QuestionList.as_view()),
    url(r'^app/question/(?P<question_id>[0-9]+)/$', views.QuestionDetail.as_view(), name='question'),
    url(r'^app/createquestion/$', TemplateView.as_view(template_name='backend.html')),
    url(r'^api/addquestion/', views.AddQuestionDetails.as_view()),
    url(r'^api/getfeedback/', views.GetFeedback.as_view()),
]

data_incubator/models.py
from django.db import models
# Model - Question to store question content,
# solution and testcase. Two boolean fields
# single_valued and coding are used to determine whether
# the question accpts a single valued solution or a code
# test_case field can be removed and files can be used to
# multiple test cases
class Question(models.Model):
    text = models.CharField(max_length=200)
    description = models.CharField(max_length=20000,default="")
    single_valued = models.BooleanField(default=True)
    coding = models.BooleanField(default=True)
    test_case = models.CharField(max_length=20000,default="")
    solution = models.CharField(max_length=200,default="")
    def __str__(self):
        return self.text

# Model - Score to store the score obtained by
# each student for a question, student_name field
# can be made into foreign key for a Student(model)
# to store the logged in user insted of a default value
class Score(models.Model):
     score_value = models.CharField(max_length=20,default=0)
     student_name = models.CharField(max_length=200,default="Nitin")
     question = models.ForeignKey(Question, on_delete=models.CASCADE)
     def __str__(self):
         return self.score_value

data_incubator/views.py
import os.path
from django.views.generic import ListView
from django.db import transaction
from rest_framework import status
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.parsers import JSONParser
from django.http import HttpResponse
from data_incubator.models import Question,Score
# Create your views here.
# Temporary test view
def index(request):
    return HttpResponse("Hello, world. You're at the temporary index page.")

# View to list all the question on main(home)page
class QuestionList(ListView):
    model = Question
    template_name = 'frontend.html'
    queryset = Question.objects.all().order_by('-id')

# view to get details of a specific question based on it id
class QuestionDetail(ListView):
    model = Question
    template_name = 'question.html'
    def get_queryset(self):
        print(self.kwargs['question_id'])
        return Question.objects.filter(id=self.kwargs.get('question_id'))

# view to process the given answer and verify the correctness
class GetFeedback(APIView):

    parser_classes = (JSONParser,)
    def get(self, request, format=None):
        pass

    @transaction.atomic
    def post(self, request, format=None):
        js = request.data
        isCorrect = False
        id = js['id']
        answer = js['answer']
        # varibale correct can be used to determine the percentage of
        # passed testcases and determine score
        correct = 1
        score_id = Score()
        que = Question.objects.get(id=id)
        if que.single_valued:
            if answer == que.solution:
                isCorrect = True
                score_id = self._add_test_scores(que,1)
        elif que.test_case:
            res = self._run_testcase(answer,que)
            if res:
                isCorrect = True
                score_id = self._add_test_scores(que,correct)
        ret_body = {}
        ret_body['flag'] = isCorrect
        ret_body['id'] = score_id.id
        ret_body['score'] = 100 * correct
        return Response(ret_body, status=status.HTTP_201_CREATED)

# Runs stored test case against the submitted code
# can be modified to run against testcases stored in file
    def _run_testcase(self,answer,que):
        testcase = que.test_case
        t_arr = testcase.split()
        ans_arr = answer.split()
        # modify code to include function call using test case
        start = ans_arr[1].index('(')
        param_arr = ans_arr[1][start:].split(',')
        func_call = "\nans = "
        func_call += ans_arr[1][:start+1]
        for i in range(len(param_arr)):
            func_call += t_arr[i]
            if i != (len(param_arr)-1):
                func_call += ','
        func_call += ')'
        print(func_call)
        answer += func_call
        # modification ends
        print(answer)
        ans = {}
        # execute code
        exec(answer,{},ans)
        if t_arr[len(param_arr)] == str(ans['ans']):
            return True
        else:
            return False

# Adds test score to Score table
    def _add_test_scores(self,que,correct):
        data = Score()
        data.question = que
        data.score = 100*correct
        data.save()
        return data

# View to add the new question to database
class AddQuestionDetails(APIView):

    parser_classes = (JSONParser,)
    def get(self, request, format=None):
        pass

    @transaction.atomic
    def post(self, request, format=None):
        js = request.data
        text = js['text']
        description = js['description']
        single_valued = js['single_valued']
        coding = js['coding']
        testcase = js['testcase']
        solution = js['solution']
        added = self._add_question(text,description,single_valued,coding,testcase,solution)
        ret_body = {}
        ret_body['snap_id'] = added.id
        return Response(ret_body, status=status.HTTP_201_CREATED)

    def _add_question(self, text,description,single_valued,coding,testcase,solution):
        data = Question()
        print("bello creating")
        data.text = text
        data.description = description
        data.single_valued = single_valued
        data.coding = coding
        data.test_case = testcase
        data.solution = solution
        print("trying to save")
        data.save()
        print("bello")
        return data

data_incubator/templates/backend.html
<!-- Backend Access page to create new questions -->
<!-- Improve Javascript so that only required input box is visible depending on question type-->
{% extends "base.html" %}
{% block content %}

<div style="align-content: center;text-align: center;" >
<div class="form-group">
    <h2>Enter your Question's Details</h2>
    <table style = "text-align: left; margin-left:auto; margin-right:auto; border-collapse:separate; border-spacing:1em;">
        <tr>
            <td><label for="Text">Question Text:</label></td>
            <td><input type="text" id="que_text"  placeholder="Ex: What is 1+1?" /></td>
        </tr>
        <tr>
            <td><label for="description">Description:</label></td>
            <td><textarea cols="50" rows="5" id="que_description" placeholder="Description"></textarea></td>
        </tr>
        <tr>
            <td><label>Specify the question type:</label></td>
        </tr>
        <tr>
            <td><label for="singleval">Single Valued:</label></td>
            <td><input type="checkbox" id="que_type_single" /></td>
        </tr>
        <tr>
            <td><label for="code">Coding:</label></td>
            <td><input type="checkbox" id="que_type_code" /></td>
        </tr>
        <tr>
            <td><label for="testcase">Testcase:</label></td>
            <td><input type="text" id="que_testcase" placeholder="1 1 2"/></td>
        </tr>
        <tr>
            <td><label for="Solution">Solution:</label></td>
            <td><input type="text" id="que_solution"  placeholder="Expected Answer"/></td>
        </tr>
    </table>
</div>
<button id="doSave" onclick="uiSaveQuestionDetails();" class="btn btn-primary">Add New Question</button>
</div>
    <script>
        document.addEventListener('DOMContentLoaded', onLoad, false);
    </script>

{% endblock %}

data_incubator/templates/base.html
<!-- Base html page to import all the css,js files and define a fixed header for all pages -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>The Data Incubator Demo</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script src="{{STATIC_URL|default:"/static/"}}js/jquery.min.js"></script>
    <link href="{{STATIC_URL|default:"/static/"}}css/bootstrap.min.css" rel="stylesheet">
    <link href="{{STATIC_URL|default:"/static/"}}css/bootstrap-demo.css" rel="stylesheet">
    <link href="{{STATIC_URL|default:"/static/"}}css/custom_style.css" rel="stylesheet">
    <link href='https://fonts.googleapis.com/css?family=Lato:400' rel='stylesheet' type='text/css'>

    <style>
        body {
            font-family: "Lato", "Helvetica Neue", "Helvetica", "Arial", sans-serif;
        }
    </style>
</head>
<body>
<!-- "nav_bar" block is used to provide navigation bar on top of homepage-->
{% block nav_bar %}
  <nav class="navbar navbar-default navbar-fixed-top main-bg">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-left" id = "navigation_links">
                <li style = "padding-right: 30px;"><a href="/app/questions">Questions</a></li>
                <li><a href="/app/createquestion">Add Question</a></li>
            </ul>
        </div>
      </div>
    </nav>
{% endblock %}
<!-- "panel-background" class is used to provide different background for homepage-->
<!-- "container-fluid-background" class is used to provide different background for other pages-->
<div class="container-fluid bg-height panel-background container-fluid-background">
{% block content %}
    <h1>Hello, world!</h1>
{% endblock %}

  <footer class="footer">
      <p class="homepage-color">&copy; The Data Incubator</p>
  </footer>
</div>


<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="{{STATIC_URL|default:"/static/"}}js/bootstrap.min.js"></script>
<script src="{{STATIC_URL|default:"/static/"}}js/data_incubator_app.js"></script>
{% block page_js_content %}

{% endblock %}

</body>
</html>

data_incubator/templates/error.html
<!--Dumb Error Page -->
{% extends "base.html" %}
{% block content %}

<div style="align-content: center; text-align: center">
    Unexpected Error Occured
</div>

{% endblock %}

data_incubator/templates/frontend.html
<!-- lists all the questions from the data base -->

{% extends "base.html" %}
{% block content %}

<div style="align-content: center; text-align: center">
    <h3>Questions List:</h3>
</div>
<div class="row">
    <div class="col-xs-10 col-sm-offset-1 col-sm-10 col-sm-offset-1 col-md-10 col-md-offset-1 col-ld-10 col-ld-offset-1">
        <br/>
        <table style = "text-align: left; margin-left:auto; margin-right:auto; border-collapse:separate; border-spacing:1em;font-size: 20px;">
            <tr>
                <th>Question</th>
                <th>Max. Score</th>
            </tr>
            {% for question in question_list %}
                <tr>
                    <td><a href="{% url 'question' question.id %}">{{ question.text }}</a></td>
                    <td>100</td>
                </tr>
            {% endfor %}

        </table>
        </div>
</div>
{% endblock %}

data_incubator/templates/question.html
<!-- Displays question statement and takes the solution -->
{% extends "base.html" %}
{% block content %}

<div style="align-content: center; text-align: center">
    <h3>Solve the Following:</h3>
</div>
<div class="row">
    <div class="col-xs-10 col-sm-offset-1 col-sm-10 col-sm-offset-1 col-md-10 col-md-offset-1 col-ld-10 col-ld-offset-1">
        <br/>
        {% for question in question_list %}
            <h2>{{ question.text }}</h2>
            <input type="text" id="que_id" style="visibility: hidden;" value="{{ question.id }}">
            <br/>
            <p style="font-size: 20px;">{{ question.description }}</p>
            {% if question.single_valued %}
                <div>
                    <label for="ans">Enter your Solution:</label>
                    <input type="text" id="que_ans" />
                </div>
            {% endif %}
            {% if question.coding %}
                <div>
                    <label for="ans">Enter your code: (Only Python code supported! Please define code in a function)</label>
                    <br/>
                    <textarea cols="50" rows="5" id="que_ans" placeholder="Enter your code"></textarea>
                </div>
            {% endif %}
        {% endfor %}
        <br/>
        <button id="doSave" onclick="uiGetFeedback();" class="btn btn-primary" >Submit Solution</button>
        <br/><br/>
        <div id="feedback"></div>
    </div>
</div>

{% endblock %}